### PR TITLE
remove_validate_delta

### PR DESCRIPTION
**Pull request by gogo2464**
fixes:
https://github.com/freenet/freenet-core/issues/1243

### CODE REVIEW

**Comment by gogo2464** [comment]
compiles in my computer if combined with the stdlib PR.

current tests already broken by older PRs.

no more tests added.

**Comment by iduartgomez** [comment]
You must probably update the stdlib submodule commit to see that it works, there is a new failing test otherwise

**Comment by iduartgomez** [comment]
Update the submodule to last stdlib `main` commit and we can check again.

**Comment by gogo2464** [comment]
I just need to push again

**Comment by iduartgomez** [comment]
Completed in #1274

**Comment by gogo2464** [comment]
painful to see such duplicated. I hope he forked me.

**Comment by iduartgomez** [comment]
Your PR was broken and as a result we had a broken incompatible version which was not in sync with stdlib. I had to finish this up sorry, next time complete the changes in one go.

**Comment by gogo2464** [comment]
nice

**Pull request closed without merging**
