### PR TITLE
create gateway

### PR DESCRIPTION
**Pull request by gogo2464**
A draft PR in order to progressively show my progress.

### CODE REVIEW

**Comment by sanity** [comment]
@gogo2464 Is this still relevant? If not could you close?

**Comment by iduartgomez** [comment]
what's the goal of this PR anyway, I think is copying stuff we already are doing and this won't do anything correctly really

**Comment by gogo2464** [comment]
Hello. Sorry I ignored you are already working on a OUT proxy or any way to access to the GET state directly.

Could you link your way please?

**Comment by iduartgomez** [comment]
But this PR is not doing that, there is 2 new paths which point to the home, and a bunch of stuff which is copied from the current command-like web socket interface. What functionality are you seeking?

**Comment by iduartgomez** [comment]
Closing cause seems like code duplication and no clear goal.

**Comment by gogo2464** [comment]
I understand. I was not successfull.

**Pull request closed without merging**
