### PR TITLE
freenet hight level API

### PR DESCRIPTION
**Pull request by gogo2464**
fixes : https://github.com/freenet/freenet-core/issues/1031

### CODE REVIEW

**Comment by gogo2464** [comment]
The program compiles.

I tested with:
```
use freenet::client_api::simple::API;

#[tokio::main]
async fn main() -> Result<(), anyhow::Error> {
    let mut api = API::new(50509);
    let out = api.update(String::from("kjgwfelkhjwfefewhjwefnjfewnlwfejlfewnj"), vec![DELTA CONTENT]);
}
```
 a cargo run returns:

```
Updating contract kjgwfelkhjwfefewhjwefnjfewnlwfejlfewnj
test: Err(update error for contract kjgwfelkhjwfefewhjwefnjfewnlwfejlfewnj, reason: missing contract parameters)
```

could someone check it please? I am 90% sure it is an isue with library call usage. Not implementing.

**Comment by iduartgomez** [comment]
Can you remove the Cargo.lock changes? Also open a PR for the sodlib changes?

**Comment by gogo2464** [comment]
2 differents PR:
- 1 for freenet core
- 2 a second for stdlib?

**Comment by gogo2464** [comment]
like this https://github.com/freenet/freenet-stdlib/pull/16 ?

**Comment by gogo2464** [comment]
I think this line is wrong:

https://github.com/freenet/freenet-core/pull/1032/files#diff-0d0493959efa2953a932a317ab5d09c1a98c80f5dcd427d4f989e879353530d9R150

could you check if the String is nicely translated to an array please?

**Comment by gogo2464** [comment]
could you review https://github.com/freenet/freenet-stdlib/pull/16 please?

**Comment by gogo2464** [comment]
> Can you remove the Cargo.lock changes? Also open a PR for the sodlib changes?

can I do cargo update?

**Comment by gogo2464** [comment]
stdl PR has been open.

@sanity I bring back the old Cargo.lock. Raises error.

could you review please?

**Comment by gogo2464** [comment]
edit: here sorry https://github.com/freenet/freenet-core/pull/1032/files#diff-57f2e85da1455a80c97c5870c54358fbc40698da837d45aff7828da4c372829bR32

**Comment by gogo2464** [comment]
might be fixed. I might misread the doc

**Comment by gogo2464** [comment]
FIXED!!!!!

The Config::conf().contracts_dir() and other functions like these correspond to /tmp/freenet instead of the real folder. 

I have to push.

We also have to fix it. I will open an issue.

**Comment by iduartgomez** [comment]
Closing this PR as we will be rethinking this after release as we improve devex

**Pull request closed without merging**
